name: Auto Spider Notice

cache:
   key: "$CI_COMMIT_REF_SLUG"
   paths:
     cache/data.txt
on:
  workflow_dispatch:
  push:
    branches:
      - main

  schedule:
    - cron: '0/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Restore cached Primes
      id: cache-primes-restore
      uses: actions/cache/restore@v3
      with:
        path: cache/data.txt
        key: "$CI_COMMIT_REF_SLUG"

    - name: Run Script
      env:
        KEY: ${{ secrets.key }}
      run: |
        python run.py

    - name: Save Primes
      id: cache-primes-save
      uses: actions/cache/save@v3
      with:
        path: cache/data.txt
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

